package com.warroom.server.model;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    ALERT_ACKNOWLEDGED,
    ALERT_FALSE_POSITIVE,
    ALERT_ESCALATED,
    INCIDENT_CREATED,
    INCIDENT_TAKEN,
    INCIDENT_STATUS_CHANGED,
    INCIDENT_COUNTERMEASURE_ADDED,
    INCIDENT_NOTE_ADDED,
    INCIDENT_REASSIGNED,
    INCIDENT_RETURNED,
    INCIDENT_CLOSED,
    AGENT_CONFIG_CHANGED,
    USER_CREATED,
    USER_DISABLED,
    USER_ENABLED
}