### Variables globales
@host = http://localhost:8080
@l1User = ahmed.11
@l1Pass = MotDePasse123

### ===================================================================
### PRÉREQUIS : CONNEXION
### ===================================================================


### 0.1 - Connexion avec le compte L1
# Les actions de qualification nécessitent le rôle L1
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "{{l1User}}",
  "password": "{{l1Pass}}"
}

> {%
    client.test("Login L1 réussi", function() {
        client.assert(response.status === 200, "Le statut devrait être 200");
    });
%}

### ===================================================================
### SCÉNARIO 1 : RÉCUPÉRATION ET FILTRAGE DES ALERTES
### ===================================================================

### 1.1 - Récupérer toutes les alertes (Paginé)
GET {{host}}/api/alerts?page=0&size=10

> {%
    client.test("Liste des alertes récupérée", function() {
        client.assert(response.status === 200, "Le statut devrait être 200");
        client.assert(response.body.content.length > 0, "Il devrait y avoir des alertes");
    });
%}

### 1.2 - Tester les filtres dynamiques (Uniquement les NEW et CRITICAL)
# Grâce à ta classe AlertSpecifications, Spring va traduire ça en SQL !
GET {{host}}/api/alerts?status=NEW&severity=CRITICAL

> {%
    client.test("Filtres dynamiques fonctionnels", function() {
        client.assert(response.status === 200, "Le statut devrait être 200");
        client.assert(response.body.content[0].severity === "CRITICAL", "L'alerte doit être CRITICAL");
        client.assert(response.body.content[0].status === "NEW", "Le statut doit être NEW");
        // On sauvegarde l'ID de cette alerte CRITICAL pour le scénario suivant
        client.global.set("alertIdToAck", response.body.content[0].id);
    });
%}

### 1.3 - Récupérer le détail d'une alerte spécifique
GET {{host}}/api/alerts/{{alertIdToAck}}

> {%
    client.test("Détail de l'alerte récupéré", function() {
        client.assert(response.status === 200, "Le statut devrait être 200");
        client.assert(response.body.alert.id == client.global.get("alertIdToAck"), "L'ID doit correspondre");
        client.assert(response.body.agent !== undefined, "Les infos de l'agent doivent être présentes");
    });
%}

### ===================================================================
### SCÉNARIO 2 : LE WORKFLOW DE L'ANALYSTE (MACHINE D'ÉTAT)
### ===================================================================

### 2.1 - Acquitter une alerte (Passage à ACKNOWLEDGED)
PUT {{host}}/api/alerts/{{alertIdToAck}}/acknowledge

> {%
    client.test("Alerte acquittée avec succès", function() {
        client.assert(response.status === 200, "Le statut devrait être 200 OK");
        client.assert(response.body.status === "ACKNOWLEDGED", "Le statut de réponse doit être ACKNOWLEDGED");
    });
%}

### 2.2 - Tenter de ré-acquitter la même alerte
# Doit renvoyer une erreur 409 (Conflict) grâce à ton IllegalStateException
PUT {{host}}/api/alerts/{{alertIdToAck}}/acknowledge

> {%
    client.test("Protection contre le double acquittement", function() {
        client.assert(response.status === 409, "Le statut devrait être 409 Conflict");
    });
%}

### 2.3 - Tenter de qualifier en Faux Positif SANS justification
# On va utiliser l'alerte ID 2 (qui est censée être NEW d'après notre SQL)
PUT {{host}}/api/alerts/2/false-positive
Content-Type: application/json

{
  "justification": ""
}

> {%
    client.test("Refus du faux positif sans justification", function() {
        client.assert(response.status === 400, "Le statut devrait être 400 Bad Request");
    });
%}

### 2.4 - Qualifier correctement en Faux Positif
PUT {{host}}/api/alerts/2/false-positive
Content-Type: application/json

{
  "justification": "Après vérification, c'est l'équipe infra qui a lancé un scan de vulnérabilité planifié."
}

> {%
    client.test("Alerte qualifiée en Faux Positif", function() {
        client.assert(response.status === 200, "Le statut devrait être 200 OK");
        client.assert(response.body.status === "FALSE_POSITIVE", "Le nouveau statut doit être FALSE_POSITIVE");
        client.assert(response.body.justification !== null, "La justification doit être sauvegardée");
    });
%}